# Generated by Django 5.0.1 on 2024-01-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='region_images/')),
                ('instrument', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=100)),
            ],
        ),
    ]
